### ISSUE TITLE
Is the bot creating multiple new labels? 

### ISSUE THREAD

**Issue by okkhoy** [nus-cs2103/cs2103-pr-bot#8] opened 2017-01-30 07:03 UTC
I see multiple FormatCheckRequested labels in the Sem2 address-book level 1 repository.

**Comment by mauris** [comment] 2017-08-03 06:21
@okkhoy I'll close this repository since it's been some time back and can't reproduce in later part of the sem. Could be a bug on Github's side.

**Closed by mauris** 2017-08-03 06:21 UTC
